version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: justs1ddy/backend:v1.0
    restart: always
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: justs1ddy/frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../frontend/:/app/result_build/
      - ./static/:/var/html/static/
      - ./media/:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  db_value:
  static_value:
  media_value: