# Generated by Django 2.2.16 on 2023-04-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230401_1813'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='%(app_label)s_%(class)s_unique',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='%(app_label)s_%(class)s_unique',
        ),
    ]
